# COGS109 - Group Project

In [34]:
# essentials
import pandas as pd
import numpy as np

# graphics
import matplotlib.pyplot as plt
import seaborn as sns

%config InlineBackend.figure_format ='retina'

## Setup
- Question: How do we predict the success of a movie given its features including budget, genres, producer, production companies, production country, etc.?


- Dataset: movie metadata from TMDB 
    - link: https://www.kaggle.com/rounakbanik/the-movies-dataset
    - number of observations: 45466

## Load Data

In [35]:
df_cr = pd.read_csv('data/credits.csv')
df_cr.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [36]:
df = pd.read_csv('data/movies_metadata.csv')
df.transpose()

/Users/yufeideng/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,0,1,2,3,4,5,6,7,8,9,...,45456,45457,45458,45459,45460,45461,45462,45463,45464,45465
adult,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', ...",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",NaN,"{'id': 96871, 'name': 'Father of the Bride Col...",NaN,NaN,NaN,NaN,"{'id': 645, 'name': 'James Bond Collection', '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
budget,30000000,65000000,0,16000000,0,60000000,58000000,0,35000000,58000000,...,0,0,0,0,0,0,0,0,0,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 35, 'name': 'Comedy'}]","[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",...,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...","[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...","[{'id': 27, 'name': 'Horror'}]","[{'id': 878, 'name': 'Science Fiction'}]","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...","[{'id': 18, 'name': 'Drama'}]","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",[],[]
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.mgm.com/view/movie/757/Goldeneye/,...,NaN,NaN,NaN,NaN,NaN,http://www.imdb.com/title/tt6209470/,NaN,NaN,NaN,NaN
id,862,8844,15602,31357,11862,949,11860,45325,9091,710,...,84419,390959,289923,222848,30840,439050,111109,67758,227506,461257
imdb_id,tt0114709,tt0113497,tt0113228,tt0114885,tt0113041,tt0113277,tt0114319,tt0112302,tt0114576,tt0113189,...,tt0038621,tt0265736,tt0252966,tt0112613,tt0102797,tt6209470,tt2028550,tt0303758,tt0008536,tt6980792
original_language,en,en,en,en,en,en,en,en,en,en,...,en,en,en,en,en,fa,tl,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,رگ خواب,Siglo ng Pagluluwal,Betrayal,Satana likuyushchiy,Queerama
overview,"Led by Woody, Andy's toys live happily in his ...",When siblings Judy and Peter discover an encha...,A family wedding reignites the ancient feud be...,"Cheated on, mistreated and stepped on, the wom...",Just when George Banks has recovered from his ...,"Obsessive master thief, Neil McCauley leads a ...",An ugly duckling having undergone a remarkable...,"A mischievous young boy, Tom Sawyer, witnesses...",International action superstar Jean Claude Van...,James Bond must unmask the mysterious head of ...,...,An unsuccessful sculptor saves a madman named ...,"In this true-crime documentary, we delve into ...",A film archivist revisits the story of Rustin ...,It's the year 3000 AD. The world's most danger...,"Yet another version of the classic epic, with ...",Rising and falling between a man and woman.,An artist struggles to finish his work while a...,"When one of her hits goes wrong, a professiona...","In a small town live two brothers, one a minis...",50 years after decriminalisation of homosexual...
popularity,21.9469,17.0155,11.7129,3.85949,8.38752,17.9249,6.67728,2.56116,5.23158,14.686,...,0.222814,0.076061,0.38645,0.661558,5.683753,0.072051,0.178241,0.903007,0.003503,0.163015
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,/e64sOI48hQXyru7naBFyssKFxVd.jpg,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,...,/yMnq9mL5uYxbRgwKqyz1cVGCJYJ.jpg,/q75tCM4pFmUzdCg0gqcOQquCaYf.jpg,/lXtoHVdej6kS1Dc7KAhw05sMos9.jpg,/4lF9LH0b0Z1X94xGK9IOzqEW6k1.jpg,/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'name': 'United Artists', 'id': 60}, {'name'...",...,"[{'name': 'Universal Pictures', 'id': 33}]",[],"[{'name': 'Neptune Salad Entertainment', 'id':...","[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...",[],"[{'name': 'Sine Olivia', 'id': 19653}]","[{'name': 'American World Pictures', 'id': 6165}]","[{'name': 'Yermoliev', 'id': 88753}]",[]
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",[],"[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]","[{'iso_3166_1': 'US', 'name': 'United States o...","[{'iso_3166_1': 'RU', 'name': 'Russia'}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]"
release_date,1995-10-30,1995-12-15,1995-12-22,1995-12-22,1995-02-10,1995-12-15,1995-12-15,1995-12-22,1995-12-22,1995-11-16,...,1946-03-29,2000-10-22,2000-10-03,1995-01-01,1991-05-13,NaN,2011-11-17,2003-08-01,1917-10-21,2017-06-09
revenue,3.73554e+08,2.62797e+08,0,8.14522e+07,7.65789e+07,1.87437e+08,0,0,6.43502e+07,3.52194e+08,...,0,0,0,0,0,0,0,0,0,0
runtime,81,104,101,127,106,170,127,97,106,130,...,65,45,30,85,104,90,360,90,87,75
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'fa', 'name': 'فارسی'}]","[{'iso_639_1': 'tl', 'name': ''}]","[{'iso_639_1': 'en', 'name': 'English'}]",[],"[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released,...,Released,Released,Released,Released,Released,Released,Released,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for...,Friends are the people who let you be yourself...,Just When His World Is Back To Normal... He's ...,A Los Angeles Crime Saga,You are cordially invited to the most surprisi...,The Original Bad Boys.,Terror goes into overtime.,No limits. No fears. No substitutes.,...,Meet...The CREEPER!,NaN,"Do you know what happened 50 years before ""The...",NaN,NaN,Rising and falling between a man and woman,NaN,A deadly game of wits.,NaN,NaN
title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Subdue,Century of Birthing,Betrayal,Satan Triumphant,Queerama
video,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
vote_average,7.7,6.9,6.5,6.1,5.7,7.7,6.2,5.4,5.5,6.6,...,6.3,7,7,3.5,5.7,4,9,3.8,0,0
vote_count,5415,2413,92,34,173,1886,141,45,174,1194,...,8,2,1,1,26,1,3,6,0,0

In [37]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

### Features
- __adult__: Indicates if the movie is X-Rated or Adult.
- __belongs_to_collection__: A stringified dictionary that gives information on the movie series the particular film belongs to.
- __budget__: The budget of the movie in dollars.
- __genres__: A stringified list of dictionaries that list out all the genres associated with the movie.
- __homepage__: The Official Homepage of the move.
- __id__: The ID of the move.
- __imdb_id__: The IMDB ID of the movie.
- __original_language__: The language in which the movie was originally shot in.
- __original_title__: The original title of the movie.
- __overview__: A brief blurb of the movie.
- __popularity__: The Popularity Score assigned by TMDB.
- __poster_path__: The URL of the poster image.
- __production_companies__: A stringified list of production companies involved with the making of the movie.
- __production_countries__: A stringified list of countries where the movie was shot/produced in.
- __release_date__: Theatrical Release Date of the movie.
- __revenue__: The total revenue of the movie in dollars.
- __runtime__: The runtime of the movie in minutes.
- __spoken_languages__: A stringified list of spoken languages in the film.
- __status__: The status of the movie (Released, To Be Released, Announced, etc.)
- __tagline__: The tagline of the movie.
- __title__: The Official Title of the movie.
- __video__: Indicates if there is a video present of the movie with TMDB.
- __vote_average__: The average rating of the movie.
- __vote_count__: The number of votes by users, as counted by TMDB

### Genres

In [38]:
import ast

In [39]:
df['genres'] = df['genres'].apply(ast.literal_eval).apply(
    lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [41]:
df['genres'].head()

0     [Animation, Comedy, Family]
1    [Adventure, Fantasy, Family]
2               [Romance, Comedy]
3        [Comedy, Drama, Romance]
4                        [Comedy]
Name: genres, dtype: object

### Budget

In [5]:
df['budget'].isnull().any()

False

### Revenue

In [6]:
df['revenue'].isnull().any()

True

### Original Language

In [8]:
df['original_language'].unique()

array(['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru',
       'sv', 'ja', 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy',
       'vi', 'cs', 'da', 'no', 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo',
       'ca', 'fi', 'th', 'sk', 'bs', 'hi', 'tr', 'is', 'ps', 'ab', 'eo',
       'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et', 'ku', 'fy', 'lv',
       'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk', 'ms',
       'sq', nan, '104.0', 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo',
       'ay', 'kn', 'eu', 'ne', 'pa', 'ky', 'gl', '68.0', 'uz', 'sm', 'mt',
       '82.0', 'hy', 'iu', 'lb', 'si'], dtype=object)

In [9]:
df[(df['original_language']=='68.0') |
   (df['original_language']=='82.0')]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-09-29,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",2014-01-01,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN