In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import linear_model
from scipy.linalg import svd
from sklearn.model_selection import KFold

In [66]:
df = pd.read_csv('data/movies_ratings.csv')

In [67]:
df = df.drop(columns=['Unnamed: 0', 'timestamp'])
df['rating_avg'] = df['rating_avg'].apply(lambda x: 2*x)

In [68]:
df

,rating_avg,belongs_to_collection,popularity,Fantasy,TV Movie,Adventure,Thriller,Western,Crime,Foreign,...,zu_lan,num_languages,Canceled,In Production,Planned,Post Production,Released,Rumored,tagline_len,video_int
0,8.666667,0,6.321801,1,0,1,0,0,0,0,...,0.0,2,0.0,0.0,0.0,0.0,1.0,0.0,28,0
1,6.000000,0,5.113205,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,36,0
2,7.000000,0,0.917777,0,0,1,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,41,0
3,8.500000,0,3.933922,0,0,0,0,0,0,0,...,0.0,2,0.0,0.0,0.0,0.0,1.0,0.0,31,0
4,8.500000,0,1.972147,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8674,10.000000,0,7.333139,0,0,0,1,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,79,0
8675,10.000000,0,6.263676,0,1,1,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,0,0
8676,6.000000,1,7.692445,1,0,1,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,29,0
8677,8.000000,0,11.243161,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,0,0
8678,1.000000,0,1.124787,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,0,0

In [69]:
df = df.dropna()
clf = linear_model.Lasso(alpha=0.1)
X = df.drop(columns=['rating_avg', 'vote_count','vote_average'])
y = df.rating_avg
res = clf.fit(X, y)

coef = clf.coef_

features = X.columns[coef!=0]
print(features)
print(len(X.columns))
print(len(features))

Index(['popularity', 'Drama', 'revenue', 'runtime', 'United States of America',
       'release_date_int', 'tagline_len'],
      dtype='object')
379
7

In [71]:
A = df.iloc[:,1:]
A.head()

,belongs_to_collection,popularity,Fantasy,TV Movie,Adventure,Thriller,Western,Crime,Foreign,Animation,...,zu_lan,num_languages,Canceled,In Production,Planned,Post Production,Released,Rumored,tagline_len,video_int
0,0,6.321801,1,0,1,0,0,0,0,0,...,0.0,2,0.0,0.0,0.0,0.0,1.0,0.0,28,0
1,0,5.113205,0,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,36,0
2,0,0.917777,0,0,1,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,41,0
3,0,3.933922,0,0,0,0,0,0,0,0,...,0.0,2,0.0,0.0,0.0,0.0,1.0,0.0,31,0
4,0,1.972147,0,0,0,0,0,0,0,0,...,0.0,1,0.0,0.0,0.0,0.0,1.0,0.0,35,0

In [ ]:

u, s, vt = svd(A, full_matrices=False)

In [ ]:
# def my_regression_CV(k, # k is the number of PCs to keep
#                      n_splits=5, # for k-fold cross-validation):
#     X = u[:,:k]
#     y = df['rating_avg']
    
#     kf = KFold(n_splits=n_splits,shuffle=True,random_state=0)
#     fold=0
#     mse_train,mse_test = np.zeros(n_splits),np.zeros(n_splits)
#     for train,test in kf.split(X):
#         mdl = LinearRegression().fit(X[train,:],y[train])
#         yhat = mdl.predict(X)
#         mse_train[fold] = np.mean( (y[train]-yhat[train])**2 ) / np.mean(y[train]**2)
#         mse_test[fold] = np.mean( (y[test]-yhat[test])**2 ) / np.mean(y[test]**2)
#         fold+=1
        
#     return mse_train,mse_test

# n_splits = 5
# k_values = np.arange(1,20)
# mse_train,mse_test = np.zeros([n_splits,len(k_values)]), np.zeros([n_splits,len(k_values)])
# ik = 0
# for k in k_values:
#     mse_train[:,ik],mse_test[:,ik] = my_regression_CV(k,n_splits)
#     ik+=1